export const isolation_place_recommendations = {
    "title": "Lugar de aislamiento",
    "question": "Características del lugar de aislamiento (si es posible)",
    "subtitle": "<p>La vivienda debe disponer de una estancia con buena ventilación y que pueda ser dedicada de forma específica para el aislamiento del caso, con posibilidad de designar un baño para uso exclusivo del paciente.</p><p>La persona aislada debe disponer de teléfono para garantizar la comunicación permanente con el personal sanitario hasta la resolución de los síntomas.</p><p>El paciente no debe convivir con personas con condiciones de salud que supongan una vulnerabilidad: personas de edad avanzada, diversidad funcional, enfermedades crónicas, inmunodeprimidas, embarazadas... Tanto el paciente como sus convivientes deben ser capaces de comprender y aplicar de forma correcta y consistente las medidas básicas de higiene, prevención y control de la infección.</p><p>El paciente deberá permanecer preferiblemente en una estancia o habitación de uso individual o, en caso de que esto no sea posible, en un lugar en el que se pueda garantizar una distancia mínima de 2 metros con el resto de los convivientes. La puerta de la habitación deberá permanecer cerrada. En caso de que sea imprescindible ir a las zonas comunes del domicilio deberá utilizar mascarilla quirúrgica y realizar higiene de manos al salir de la habitación. Se mantendrán bien ventiladas las zonas comunes.</p><p>La estancia o habitación deberá tener una ventilación adecuada directa a la calle. No deben existir corrientes forzadas de aire provenientes de sistemas de calor o refrigeración.</p><p>Deberá disponer de un baño para uso exclusivo del paciente, o en su defecto, deberá ser limpiado con lejía doméstica tras cada uso que haga el paciente.</p><p>Sería importante que pudiese disponer de un intercomunicador (como los utilizados para la vigilancia de los bebés) para comunicarse con los familiares, sin necesidad de salir de la habitación. También se puede hacer a través del móvil.</p><p>En el interior de la estancia o habitación deberá colocarse un cubo de basura con tapa de apertura de pedal y en su interior una bolsa de plástico que cierre herméticamente para los residuos.</p><p>Se recomienda disponer utensilios de aseo de uso individual y de productos para la higiene de manos como jabón o solución hidroalcohólica.</p><p>Las toallas deberán cambiarse periódicamente siempre que se encuentren húmedas.</p><p>La persona enferma deberá seguir en todo momento las medidas de higiene respiratoria: cubrirse la boca y la nariz al toser o estornudar con pañuelos desechables o el codo flexionado, y lavarse las manos inmediatamente después.</p><p>La persona enferma no deberá recibir visitas durante el periodo de aislamiento.</p>",
    "multicheck": false,
    "showExitButton": true,
    "children": [
    ]
}



