/**
 * coronavirus-server
 * coronavirus-server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeolocationFields { 
  [key: string]: object | any;


    id?: boolean;
    latitude?: boolean;
    longitude?: boolean;
    accuracy?: boolean;
    altitude?: boolean;
    bearing?: boolean;
    speed?: boolean;
    created?: boolean;
    patientId?: boolean;
}

