/**
 * coronavirus-server - coronavirus-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (Schema options: { title: \'NewHealthCenter\', exclude: [ \'id\' ] })
 */
export interface NewHealthCenter { 
  [key: string]: object | any;


    name: string;
    address: string;
    postalCode: string;
    latitude?: number;
    longitude?: number;
}

