/**
 * coronavirus-server
 * coronavirus-server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TestQuestionFields { 
  [key: string]: object | any;


    id?: boolean;
    questionId?: boolean;
    title?: boolean;
    subtitle?: boolean;
    multicheck?: boolean;
    question?: boolean;
    target?: boolean;
    children?: boolean;
}

