/**
 * coronavirus-server
 * coronavirus-server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TestAppointmentScopeFilter } from './testAppointmentScopeFilter';


export interface TestAppointmentIncludeFilterItems { 
    relation?: string;
    scope?: TestAppointmentScopeFilter;
}

