export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './bluetoothLeAdvertisementController.service';
import { BluetoothLeAdvertisementControllerService } from './bluetoothLeAdvertisementController.service';
export * from './documentController.service';
import { DocumentControllerService } from './documentController.service';
export * from './geolocationController.service';
import { GeolocationControllerService } from './geolocationController.service';
export * from './healthCenterController.service';
import { HealthCenterControllerService } from './healthCenterController.service';
export * from './leaveRequestController.service';
import { LeaveRequestControllerService } from './leaveRequestController.service';
export * from './patientController.service';
import { PatientControllerService } from './patientController.service';
export * from './pingController.service';
import { PingControllerService } from './pingController.service';
export * from './policeOfficerController.service';
import { PoliceOfficerControllerService } from './policeOfficerController.service';
export * from './sanitarianController.service';
import { SanitarianControllerService } from './sanitarianController.service';
export * from './testAppointmentController.service';
import { TestAppointmentControllerService } from './testAppointmentController.service';
export * from './testQuestionController.service';
import { TestQuestionControllerService } from './testQuestionController.service';
export * from './testResultController.service';
import { TestResultControllerService } from './testResultController.service';
export const APIS = [AuthControllerService, BluetoothLeAdvertisementControllerService, DocumentControllerService, GeolocationControllerService, HealthCenterControllerService, LeaveRequestControllerService, PatientControllerService, PingControllerService, PoliceOfficerControllerService, SanitarianControllerService, TestAppointmentControllerService, TestQuestionControllerService, TestResultControllerService];
