/**
 * coronavirus-server - coronavirus-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (Schema options: { title: \'NewSanitarian\', exclude: [ \'id\' ] })
 */
export interface NewSanitarian { 
  [key: string]: object | any;


    uniqueId: string;
    firstName: string;
    lastName: string;
    hash: string;
    documentNumber: string;
    age: number;
    street: string;
    apartment?: string;
    city: string;
    postalCode: string;
    position: string;
    created?: string;
    updated?: string;
}

