/**
 * coronavirus-server - coronavirus-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { PoliceOfficerLogin } from '../model/policeOfficerLogin';
import { PoliceOfficerWithRelations } from '../model/policeOfficerWithRelations';
import { SanitarianLogin } from '../model/sanitarianLogin';
import { SanitarianWithRelations } from '../model/sanitarianWithRelations';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class AuthControllerService {

    protected basePath = 'http://localhost:3000';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * @param policeOfficerLogin 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public authControllerPoliceOfficerLogin(policeOfficerLogin?: PoliceOfficerLogin, observe?: 'body', reportProgress?: boolean): Observable<PoliceOfficerWithRelations>;
    public authControllerPoliceOfficerLogin(policeOfficerLogin?: PoliceOfficerLogin, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PoliceOfficerWithRelations>>;
    public authControllerPoliceOfficerLogin(policeOfficerLogin?: PoliceOfficerLogin, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PoliceOfficerWithRelations>>;
    public authControllerPoliceOfficerLogin(policeOfficerLogin?: PoliceOfficerLogin, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PoliceOfficerWithRelations>(`${this.configuration.basePath}/auth/police-officers`,
            policeOfficerLogin,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param sanitarianLogin 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public authControllerSanitarianLogin(sanitarianLogin?: SanitarianLogin, observe?: 'body', reportProgress?: boolean): Observable<SanitarianWithRelations>;
    public authControllerSanitarianLogin(sanitarianLogin?: SanitarianLogin, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SanitarianWithRelations>>;
    public authControllerSanitarianLogin(sanitarianLogin?: SanitarianLogin, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SanitarianWithRelations>>;
    public authControllerSanitarianLogin(sanitarianLogin?: SanitarianLogin, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<SanitarianWithRelations>(`${this.configuration.basePath}/auth/sanitarians`,
            sanitarianLogin,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
